### prometheus.yml ###

global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these extra labels to all time-series collected by this Prometheus instance.
  external_labels:
    monitor: 'infra_label'

rule_files:
  - '/etc/prometheus/alert.rules'

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: "node"
    scrape_interval: 5s
    target_groups:
      - targets: ['159.8.96.212:9100']

  - job_name: "cadvisor"
    scrape_interval: 5s
    target_groups:
      - targets: ['159.8.96.212:8888']

  - job_name: "haproxy"
    scrape_interval: 5s
    target_groups:
      - targets: ['159.8.96.212:9101']
